export const cursorVariants = {
  default: (mouseX: number, mouseY: number) => ({
    opacity: 0,
    height: 0,
    width: 0,
    scale: 0,
    fontSize: '16px',
    backgroundColor: 'transparent',
    x: mouseX,
    y: mouseY,
  }),
  project: (mouseX: number, mouseY: number) => ({
    opacity: 1,
    scale: 1,
    backgroundColor: '#000',
    color: '#fff',
    height: 80,
    width: 80,
    fontSize: '18px',
    x: mouseX - 32,
    y: mouseY - 32,
  }),
  contact: (mouseX: number, mouseY: number) => ({
    opacity: 1,
    scale: 1,
    backgroundColor: '#FFBCBC',
    color: '#000',
    height: 80,
    width: 80,
    fontSize: '32px',
    x: mouseX - 48,
    y: mouseY - 48,
  }),
}
