import type { Metadata } from 'next'
import '../styles/globals.scss'
import { Nunito } from 'next/font/google'
import { ThemeProvider } from '@/providers/ThemeProvider'
import { cn } from '@/lib/utils'

const nunito = Nunito({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-heading2',
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// import { seoData } from '../components/contants/seo-data'

// export const metadata: Metadata = {
//   metadataBase: new URL('https://phongphan.xyz'),
//   ...seoData,
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          'bg-light dark:bg-dark',
          nunito.variable,
          nunito.className
        )}
      >
        <ThemeProvider attribute='class' defaultTheme='dark' enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
